//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEPSClientInstallService_Master.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEPSClientInstallService_Master.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin
        ///create database TylerClientIMS;
        ///end.
        /// </summary>
        internal static string _1_Create_DB {
            get {
                return ResourceManager.GetString("_1_Create_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[EnrolledInstanceType]
        ///(
        ///	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
        ///    [InstanceType] NCHAR(50) NULL
        ///)
        ///.
        /// </summary>
        internal static string _2_1_CreateEnrolledInstanceType {
            get {
                return ResourceManager.GetString("_2_1_CreateEnrolledInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[errorLog]
        ///(
        ///	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
        ///    [ErrorMessage] NVARCHAR(MAX) NOT NULL, 
        ///    [ErrorDate_Time] DATETIME2 NOT NULL DEFAULT (GETDATE())
        ///)
        ///.
        /// </summary>
        internal static string _2_2_CreateErrorLog {
            get {
                return ResourceManager.GetString("_2_2_CreateErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[InstalledCatalog]
        ///(
        ///	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
        ///    [Client_ID] INT NOT NULL, 
        ///    [SQLCompact3532_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [SQLCompact3564_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [SQLCompact0464_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [SQLCLR200832_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [SQLCLR200864_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [ScenePD_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [Updater_Installed] BIT NOT NULL DEFAULT 0, 
        ///    [GISC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2_3_CreateInstalledCatalog {
            get {
                return ResourceManager.GetString("_2_3_CreateInstalledCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Clients]
        ///(
        ///	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
        ///    [ClientName] NVARCHAR(MAX) NOT NULL, 
        ///    [PassedHealthCheck] BIT NOT NULL DEFAULT 0, 
        ///    [MostRecentHealthCheckDate_Time] DATETIME2 NULL, 
        ///    [InstalledCatalog_ID] INT NULL, 
        ///    [MostRecentInstallDate_Time] DATETIME2 NULL, 
        ///    [EnrolledInstanceType_ID] INT NOT NULL DEFAULT 1, 
        ///    [InitialCreationDate_Time] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
        ///    [Date_TimeModified] DATETIME2 NULL
        ///)
        ///.
        /// </summary>
        internal static string _2_CreateClients {
            get {
                return ResourceManager.GetString("_2_CreateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert INTO TylerClientIMS.dbo.EnrolledInstanceType
        ///VALUES (&apos;UNINSTALLED&apos;)
        ///insert INTO TylerClientIMS.dbo.EnrolledInstanceType
        ///VALUES (&apos;PROD&apos;)
        ///insert INTO TylerClientIMS.dbo.EnrolledInstanceType
        ///VALUES (&apos;TEST&apos;)
        ///insert INTO TylerClientIMS.dbo.EnrolledInstanceType
        ///VALUES (&apos;TRAIN&apos;).
        /// </summary>
        internal static string _3_1_PopulateEnrolledInstanceType {
            get {
                return ResourceManager.GetString("_3_1_PopulateEnrolledInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[GetClientByID]
        ///	@id int
        ///AS
        ///	begin
        ///	select * from TylerClientIMS.dbo.Clients
        ///	where Id = @id
        ///	end
        ///.
        /// </summary>
        internal static string CreateSPGetClientByID {
            get {
                return ResourceManager.GetString("CreateSPGetClientByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[GetClientMachineProfiles]
        ///	
        ///AS
        ///	begin
        ///	Select * from dbo.Clients
        ///	end
        ///.
        /// </summary>
        internal static string CreateSPGetClientMachineProfiles {
            get {
                return ResourceManager.GetString("CreateSPGetClientMachineProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[GetInstalledCatalog]
        ///	
        ///AS
        ///	begin
        ///	Select * from dbo.InstalledCatalog
        ///	end.
        /// </summary>
        internal static string CreateSPGetInstalledCatalog {
            get {
                return ResourceManager.GetString("CreateSPGetInstalledCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[GetTop50Errors]
        ///	
        ///AS
        ///	begin
        ///	SELECT TOP (50) [Id]
        ///      ,[ErrorMessage]
        ///      ,[ErrorDate_Time]
        ///  FROM [TylerClientIMS].[dbo].[errorLog]
        ///	end
        ///.
        /// </summary>
        internal static string CreateSPGetTop50Error {
            get {
                return ResourceManager.GetString("CreateSPGetTop50Error", resourceCulture);
            }
        }
    }
}
